Footer
erikacarvalho/webdev.versionamento pull request #12
Opened 2020-08-07 04:43 UTC by vmaziero

Gente, tive dificuldade em commitar meu diretório aqui e acabei fazendo duas vezes, vejam se conseguem visualizar certinho, caso contrário eu tento novamente. Adicionei o footer mas queria saber se colocamos algum tipo de link também para ficar mais incrementado.

2020-08-07 12:46 UTC, amandabrbz requested changes
Oi Vic, precisa dar uma olhadinha nos seus arquivos, principalmente no html e css pois está vindo coisas de outras branches e tb caracteres especiais que vão quebrar o layout

2020-08-07 12:46 UTC, amandabrbz commented on index.html
> +<<<<<<< .mine
```suggestion
<<<<<<< .mine
```suggestion
<<<<<<< .mine
```
```

Vic, alguma coisa aconteceu aqui, acho que pode ter dado algum problema e ter vindo caracteres especiaris

2020-08-07 12:46 UTC, amandabrbz commented on index.html
> +</html>>>>>>>> .r22
Vic aqui tb deu ruim com esse >>>>> .r22

2020-08-07 12:46 UTC, amandabrbz commented on style.css
> +<<<<<<< .mine
Caracter especial

2020-08-07 12:46 UTC, amandabrbz commented on style.css
> +}>>>>>>> .r22
Caracter especial

2020-08-07 13:53 UTC, erikacarvalho requested changes
acredito que o ideal seria entregar nesse pull request apenas o que tem no protótipo, e depois vemos se vamos adicionar mais alguma coisa.

as marcações dos conflitos estão commitadas no seu código, precisamos consertar essa parte antes de mergear!

2020-08-08 00:05 UTC, vmaziero commented
Pessoal, fiz a branch no lugar errado e tivemos alguns conflitos, gerando esses caracteres especiais. Corrigi o local onde deveria ter clonado a pasta e acertei os arquivos para não gerar conflitos.

2020-08-08 00:44 UTC, vmaziero commented
Gente, fiz um rebase para resolver os conflitos dos arquivos index.html e style.css, @erikacarvalho @amandabrbz vocês poderiam revisar?

2020-08-08 01:00 UTC, amandabrbz commented
Oi Vic, ainda estamos com conflitos no arquivo index.html talvez seja pela criação da branch. Vamos fechar e fazer novamente?

2020-08-08 01:00 UTC, closed without merging