inclui imagem de layout ao README.md
erikacarvalho/webdev.versionamento pull request #4
Opened 2020-06-14 20:40 UTC by vmaziero

adiciona a imagem do layout que será seguido ao arquivo README.md para contribuir para a documentação do projeto.

2020-06-14 20:43 UTC, amandabrbz commented
não veio a atualização do readme

2020-06-14 20:45 UTC, amandabrbz requested changes
inclusão da imagem ao readme não foi alterada, só veio a imagem, por favor subir o arquivo salvo.

2020-06-14 21:00 UTC, amandabrbz approved these changes
Caminho alterado!

2020-06-16 01:33 UTC, erikacarvalho approved these changes
ótima contribuição para a documentação do nosso projeto, obrigada @vmaziero ☺️

2020-06-16 01:39 UTC, merged